### ISSUE TITLE
make-req

### ISSUE THREAD

**Issue by ilevd** [jcf/oauth-one#7]
Very nice, but how can I make request after auth with oauth_token to e.g update twitter status?

I tried as in documentation but I got an error: jjava.lang.AssertionError: Assert failed: (sorted? params)

I saw tests and found:
```clojure
request (sign-request
                 consumer
                 {:request-method :get
                  :url
                  (str "https://api.twitter.com/"
                       "1.1/account/verify_credentials.json?"
                       "include_entities=false&"
                       "include_email=true")
                  :query-params {"skip_status" "true"}
                  :oauth-headers
                  (sorted-map
                   "oauth_consumer_key" "key"
                   "oauth_nonce" "nonce-nonce"
                   "oauth_signature_method" "HMAC-SHA1"
                   "oauth_timestamp" "1461663703"
                   "oauth_token" "token"
                   "oauth_version" "1.0")}
"token-secret")
```

I replaced data with my own and I got another error again.

UPDATE: I found an typo error, everything's ok, but some wrapper for making requests will be good.

**Comment by jcf** [comment]
@ilevd you can use [`sign-request`](https://github.com/jcf/oauth-one/blob/330638809368a51ef82b8cf94ac93f271219101b/src/oauth/one.clj#L260-L294) to create a signed request map like so:

``` clj
(s/defn me-request :- Request
  [consumer {:keys [token secret]}]
  (one/sign-request
   consumer
   {:oauth-headers (merge (one/make-oauth-headers consumer)
                          {"oauth_token" token})
    :request-method :get
    :url (str "https://api.twitter.com/1.1/account/verify_credentials.json?"
              (ring.util.codec/form-encode {"include_email" "true"
                                            "include_entities" "true"
                                            "skip_status" "true"}))}
   secret))
```

Unfortunately, I'm not sure I can make it much easier to produce request maps, but let me give it some thought.

P.S. Sorry for the delay in my response. I need to check me notification settings!
